apiVersion: v1
name: nodeapp
description: A sample node
version: 0.0.6
keywords:
  - stakater
  - node
home: https://github.com/stakater-lab/nodeapp
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io