kubernetes:
  host: https://kubernetes.default

nodeapp:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.0.5
  deployment:
    replicas: 1
    podLabels:      
      app: stakater-nodeapp
    containerName: nodeapp
    image:
      name: docker.tools.stackator.com:443/stakater/nodeapp
      tag: v0.0.5
